import type { Metadata } from "next";
import { Source_Sans_3 , JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/app/_sections/Footer";

const fontSans = Source_Sans_3({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sayid's Portofolio",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} ${fontMono.variable} antialiased`}>
        <div
        // className="bg-gradient-to-b from-[#0f172a] to-[#36445c]"
        >
          {children}
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}


