import type { Metadata } from "next";
import { Source_Sans_3 , JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./_sections/Footer";

const fontSans = Source_Sans_3({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sayid's Portofolio",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} ${fontMono.variable} antialiased`}>
        <div className="min-h-screen flex flex-col mx-auto max-w-6xl">
          <div className="flex-1 flex flex-col items-center justify-center pb-10">
            {children}
          </div>
          <div className=" w-full border-t border-gray-200">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}


